server:
  port: 9999
  context-path: /uaa
  
       
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    org:
      springframework:
         security: DEBUG

spring:
  data:
    mongodb:
      uri: mongodb://test:123456@${mongo.host:localhost}:27017/test
      repositories:
        enabled: true
    rest:
      enable-enum-translation: true
      
  cloud:
    stream:
      bindings:
        loginSuccessOutputChannel:
          destination: loginSuccess
        removeUserOutputChannel:
          destination: removeUser
        retryEmailActivatedOutputChannel:
          destination: retryEmailActivated
          
          
          
  rabbitmq:
    dynamic: true
    host: ${rabbit.host:localhost}
    port: 5672
    username: wfij
    password:  kkslcm8923s
    virtual-host: /wfij
    listener:
     
      #max pool size of thread is 10
      max-concurrency: 10
      #核心的listen thread 是3 
      concurrency: 5
      # the container will acknowledge the message automatically, unless the MessageListener throws an exception. Note that acknowledgeMode is complementary to channelTransacted - if the channel is transacted then the broker requires a commit notification in addition to the ack. This is the default mode. See also txSize.
      acknowledge-mode: auto
      auto-startup: true
      #The number of messages to accept from the broker in one socket frame
      prefetch: 5
      #When used with acknowledgeMode AUTO, the container will attempt to process up to this number of messages before sending an ack 
      transaction-size: 5
       

 # custom jwt varietes 
jwtOfReadAndWrite:
  clientId: kksdi2388wmkwe
  clientSecret: kksd23isdmsisdi2
  autoApproval: true
  scopes: 
     - read
     - write
  grantTypes: 
     - authorization_code 
     - refresh_token 
     - password
  resourceIds:
     - ReadAndWriteResource
   
   #设定固定清零时间为6个小时，最大的尝试失败的次数为10次，10次后，锁定ip 24小时。  
LoginAttempt:
  maxAttemptTimes: 10
  timeOfPerid: 1
  timeOfLock: 3
  
  

  
  