server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  
management:
  context-path: /adminEnv
  security:
    enabled: true
    
    
spring:
  aop:
    proxy-target-class: true
  redis:
    database: 2
    host: ${redis.host:localhost}
    port: 6379
    password: 29c4181fb842b5f24a3103dbd2ba17accb1f7e3c8f198689821f7955401ab921
    pool:
      max-idle: 300        #数据库链接最大空闲数,超过空闲时间，数据库连接将被标记为不可用，然后被释放。设为0表示无限制。
      max-active: 600      #连接池的最大数据库连接数。设为0表示无限制。
      max-wait:   5000     #最大等待毫秒数, 单位为 ms, 超过时间会出错误信息  

  data:
    mongodb:
      uri: mongodb://test:123456@${mongo.host:localhost}:27017/test
      repositories:
        enabled: true    
    
security:
  basic:
    enabled: false
  user:
    password: none
  oauth2:
    sso:
      login-path: /login
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApVuOPKLwgnZxosn1zUH35nHq0bTxbcky8y9VgYg+1/XAWj6hPftDyUIXcH2vaRauoJxCf6QtpID3kcQCGVFvzkrQrNT1+2y+OjqKMmgZPe6EF6qd+1djqgfSzOSQuyIrFfhmMO84KMhyuL6wZnq0fqgqIZIXmzzyd5j12JL3jIHxsv8m5b7Crk+XuQToKCId1rTXB17t+ZmNjc6TXkmdcsCqiBRbKZ7N//VH33nNIxbFHF1uFEDrdLI2ziG/iGt9cS9dVvecgLgmPaE45ALgbv8WQycEMjCD/jopfhb2u+ybcOAEoH1pzjX4WHEVoGjVadyBE8hq9U4aH1x+Cji0kwIDAQAB
          -----END PUBLIC KEY-----
          
  
zuul:
  routes:
    property-signup: /property-signup/**
    user-account: /user-account/**
    auth-server: /auth-server/**
    email-activate: /email-activate/**
    #password-reset: /recover/**
  #add-proxy-headers: true
    
    
    
    

front:
  asset-host: ${domain.name:localhost}:3000
  asset-manifest-url: http://${domain.name:localhost}/manifest.json      
  



      