server:
  port: 8004


spring:
  data:
    mongodb:
      uri: mongodb://test:123456@${mongo.host:localhost}:27017/test
      repositories:
        enabled: true
     
  cloud:
    stream:
      bindings: 
        emailActivatedInputChannel:
          destination: emailActivated
          content-type: application/x-java-object; type=com.xdidian.keryhu.domain.EmailActivatedDto;
        removeUserOutputChannel:
          destination: removeUser
        emailActivatedSuccessOutputChannel:
          destination: emailActivatedSuccess
        resendOutputChannel:
          destination: resendEmailActivate
          contentType: application/json
        
          
  rabbitmq:
    dynamic: true
    host: ${rabbit.host:localhost}
    port: 5672
    username: wfij
    password:  kkslcm8923s
    virtual-host: /wfij
    listener:
     
      #max pool size of thread is 100
      max-concurrency: 100
      #核心的listen thread 是3 
      concurrency: 50
      # the container will acknowledge the message automatically, unless the MessageListener throws an exception. Note that acknowledgeMode is complementary to channelTransacted - if the channel is transacted then the broker requires a commit notification in addition to the ack. This is the default mode. See also txSize.
      acknowledge-mode: auto
      auto-startup: true
      #The number of messages to accept from the broker in one socket frame
      prefetch: 50
      #When used with acknowledgeMode AUTO, the container will attempt to process up to this number of messages before sending an ack 
      transaction-size: 50
  
      
security:
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApVuOPKLwgnZxosn1zUH35nHq0bTxbcky8y9VgYg+1/XAWj6hPftDyUIXcH2vaRauoJxCf6QtpID3kcQCGVFvzkrQrNT1+2y+OjqKMmgZPe6EF6qd+1djqgfSzOSQuyIrFfhmMO84KMhyuL6wZnq0fqgqIZIXmzzyd5j12JL3jIHxsv8m5b7Crk+XuQToKCId1rTXB17t+ZmNjc6TXkmdcsCqiBRbKZ7N//VH33nNIxbFHF1uFEDrdLI2ziG/iGt9cS9dVvecgLgmPaE45ALgbv8WQycEMjCD/jopfhb2u+ybcOAEoH1pzjX4WHEVoGjVadyBE8hq9U4aH1x+Cji0kwIDAQAB
          -----END PUBLIC KEY----- 


  

#重复发送email激活的次数
activatedProperties:
  maxSendTimes: 6
  resendUrl: http://${domain.name:localhost}:8080/email-activate/email/resend?email=
  reregisterUrl: http://${domain.name:localhost}:8080/email-activate/email/reregister?email=
  loginUrl: redirect:http://${domain.name:localhost}:9999/uaa
  defaultRegisterUrl: redirect:http://${domain.name:localhost}:8080/register
  registerResultUrl: redirect:http://${domain.name:localhost}:8080/register/result