server:
  port: 8004


spring:
  data:
    mongodb:
      uri: mongodb://test:123456@${mongo.host:localhost}:27017/test
      repositories:
        enabled: true
     
  cloud:
    stream:
      bindings: 
        emailActivatedInputChannel:
          destination: emailActivated
          content-type: application/x-java-object; type=com.xdidian.keryhu.domain.EmailActivatedDto;
        removeUserOutputChannel:
          destination: removeUser
        emailActivatedSuccessOutputChannel:
          destination: emailActivatedSuccess
        resendOutputChannel:
          destination: resendEmailActivate
          contentType: application/json
        
          
  
  messages:
    basename: locale/messages_zh_CN
    encoding: UTF-8
    cache-seconds: 3600
          

  

#重复发送email激活的次数
activated:
  max_send_times: 6
  send_cycle_minutes: 2
  resend_url: http://${domain.name:localhost}:8080/email-activate/email/resend?email=
  re_signup_url: http://${domain.name:localhost}:8080/email-activate/email/signup?email=
  login_url: redirect:http://${domain.name:localhost}:9999/uaa/login
  default_signup_url: redirect:http://${domain.name:localhost}:8080/signup
  after_signup_url: redirect:http://${domain.name:localhost}:8080/signup/result