server:
  port: 8001


spring:
  data:
    mongodb:
      uri: mongodb://test:123456@${mongo.host:localhost}:27017/test
      repositories:
        enabled: true
    rest:
      enable-enum-translation: true
      
  cloud:
    stream:
      bindings: 
        loginSuccessInputChannel: 
          destination: loginSuccess
        removeUserInputChannel:
          destination: removeUser
        propertyRegisterSaveInputChannel: 
          destination: propertyRegisterSave
          content-type: application/x-java-object; type=com.xdidian.keryhu.domain.PropertyRegisterDto
        activatedSuccessInputChannel:
          destination: activatedSuccess
           
        
          
  
  
      

 
  

