server:
  port: 8006


spring:
  data:
    mongodb:
      uri: mongodb://test:123456@${mongo.host:localhost}:27017/test
      repositories:
        enabled: true
    rest:
      enable-enum-translation: true
      
           
        
          
  
  
      

 
  

